const data = {
    nodes: [
        { name: 'Bluebell Pineda (Nurse)', id: 0 },
        { name: 'Alexa Duke', id: 1 },
        { name: 'Katharine Broadhurst', id: 2 },
        { name: 'Aman Myers (Tech)', id: 3 },
        { name: 'Corban Davila', id: 4 },
        { name: 'Isla-Grace Dotson', id: 5 },
        { name: 'Aishah Finley', id: 6 },
        { name: 'Stacey Carr (Nurse)', id: 7 },
        { name: 'Zacharia Browning (Nurse)', id: 8 },
        { name: 'Jevon Hester', id: 9 },
        { name: 'Aiysha Stott', id: 10 },
        { name: 'Leon Collier (Tech)', id: 11 },
        { name: 'Dahlia Mcleod', id: 12 },
        { name: 'Laiba Guevara', id: 13 },
        { name: 'Stefanie Joseph', id: 14 },
        { name: 'Mamie Mclaughlin (Nurse)', id: 15 },
        { name: 'Bluebell Pineda', id: 16 },
        { name: 'Alexa Duke', id: 17 },
        { name: 'Katharine Broadhurst', id: 18 },
        { name: 'Aman Myers', id: 19 },
        { name: 'Corban Davila', id: 20 },
        { name: 'Isla-Grace Dotson', id: 21 },
        { name: 'Aishah Finley', id: 22 },
        { name: 'Stacey Carr', id: 23 },
        { name: 'Zacharia Browning', id: 24 },
        { name: 'Jevon Hester', id: 25 },
        { name: 'Aiysha Stott', id: 26 },
        { name: 'Leon Collier', id: 27 },
        { name: 'Dahlia Mcleod', id: 28 },
        { name: 'Laiba Guevara', id: 29 },
        { name: 'Stefanie Joseph', id: 30 },
        { name: 'Mamie Mclaughlin', id: 31 },
    ],
    links: [
        // { source: 0, target: 1 },
        { source: 0, target: 2 },
        { source: 3, target: 4 },
        { source: 3, target: 5 },
        { source: 3, target: 6 },
        { source: 5, target: 0 },
        { source: 7, target: 6 },
        { source: 7, target: 4 },
        { source: 8, target: 9 },
        { source: 8, target: 10 },
        // { source: 8, target: 12 },
        { source: 11, target: 13 },
        { source: 11, target: 14 },
        { source: 13, target: 8 },
        { source: 13, target: 8 },
        { source: 15, target: 12 },
        { source: 15, target: 1 },
    ],
}

export default data
